name: SCOP CI

on:
  push: # S'activera sur TOUTES les branches à chaque push
  pull_request:
    branches: [ "main" ] # S'activera quand on cherchera à fusionner sur main

jobs:
  test_and_lint:
    name: Fedora Build & Test
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          dnf update -y
          dnf install -y gcc curl vulkan-headers vulkan-loader-devel

      - name: Install Rust toolchain (rustup)
        # On utilise l'installateur officiel pour avoir cargo, rustfmt et clippy parfaitement liés
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --component rustfmt clippy
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Unit Tests
        run: cargo test --verbose
