name: SCOP CI

on:
  push: 
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_lint:
    name: Fedora Build & Test
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies (C, C++, Vulkan)
        # On utilise dnf UNIQUEMENT pour les dépendances de l'OS
        run: |
          dnf update -y
          dnf install -y gcc gcc-c++ make vulkan-headers vulkan-loader-devel

      - name: Setup Rust Toolchain
        # L'action officielle qui gère parfaitement Rust, Cargo, Clippy et rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Unit Tests
        run: cargo test --verbose
